name: Setup and test

on: [ push, pull_request ]

jobs:
  tests:
    name: Composer setup and tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --no-suggest
      - name: Run tests
        run: |
          composer validate --strict

      - name: Run pest tests
        run: |
          bash install.sh
          composer test
